LHS = [
'program_prime',
'program',
'declaration_list',
'declaration_list',
'declaration',
'declaration',
'var_declaration',
'var_declaration',
'fun_declaration',
'fun_declaration',
'params',
'params',
'param_list',
'param_list',
'param',
'param',
'compound_stmt',
'local_declarations',
'local_declarations',
'statement_list',
'statement_list',
'statement',
'statement',
'statement',
'statement',
'statement',
'expression_stmt',
'expression_stmt',
'selection_stmt',
'iteration_stmt',
'return_stmt',
'return_stmt',
'expression',
'expression',
'var',
'var',
'simple_expression',
'simple_expression',
'relop',
'relop',
'additive_expression',
'additive_expression',
'addop',
'addop',
'term',
'term',
'factor',
'factor',
'factor',
'factor',
'call',
'args',
'args',
'arg_list',
'arg_list',
]

RHS = [
['program'],
['declaration_list','EOF'],
['declaration_list','declaration'],
['declaration'],
['var_declaration'],
['fun_declaration'],
['int','ID', ';'],
['int','ID', '[', 'NUM', ']', ';'],
['int','ID','(', 'params', ')', 'compound_stmt'],
['void','ID','(', 'params', ')', 'compound_stmt'],
['param_list'],
['void'],
['param_list',',','param'],
['param'],
['int', 'ID'],
['int','ID', '[', ']'],
['{', 'local_declarations','statement_list', '}'],
['local_declarations','var_declaration'],
[],
['statement_list','statement'],
[],
['expression_stmt'],
['compound_stmt'],
['selection_stmt'],
['iteration_stmt'],
['return_stmt'],
['expression',';'],
[';'],
['if','(','expression',')','statement','else','statement'],
['while','(','expression',')','statement'],
['return', ';'],
['return', 'expression', ';'],
['var', '=', 'expression'],
['simple_expression'],
['ID'],
['ID', '[', 'expression', ']'],
['additive_expression','relop','additive_expression'],
['additive_expression'],
['<'],
['=='],
['additive_expression','addop','term'],
['term'],
['+'],
['-'],
['term', '*', 'factor'],
['factor'],
['(','expression',')'],
['var'],
['call'],
['NUM'],
['ID', '(', 'args', ')'],
['arg_list'],
[],
['arg_list',',','expression'],
['expression']
]

follow = {
'declaration': ['EOF', 'void', 'int'],
'params': [')'],
'compound_stmt': ['ID', 'EOF', 'if', '(', 'int', 'NUM', 'return', 'else', 'void', 'while', '{', ';', '}'],
'declaration_list': ['EOF', 'void', 'int'],
'expression_stmt': ['return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # rsdfw({;}n
'fun_declaration': ['EOF', 'void', 'int'], # evi
'statement': ['return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # rsdfw({;}n
'selection_stmt': ['return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # rsdfw({;}n
'iteration_stmt': ['return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # rsdfw({;}n
'var': ['==', ')', '*', ';', '+', '<', ',', '=', '-', ']'], # q)*;+<,=-]
'simple_expression': [')', ';', ',', ']'], # );,]
'local_declarations': ['return', 'ID', 'if', 'while', '(', 'int', '{', ';', '}', 'NUM'], # rdfw(i{;}n
'term': ['==', ')', '*', ';', '+', '<', ',', '-', ']'], # q)*;+<,-]
'addop': ['ID', '(', 'NUM'], # d(n
'relop': ['ID', '(', 'NUM'], # d(n
'program': ['$'], # $
'additive_expression': ['==', ')', ';', '+', '<', ',', '-', ']'], # q);+<,-]
'return_stmt': ['return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # rsdfw({;}n
'statement_list': ['return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], #rdfw({;}n
'factor': ['==', ')', '*', ';', '+', '<', ',', '-', ']'], # q)*;+<,-]
'var_declaration': ['return', 'ID', 'EOF', 'void', 'if', 'while', '(', 'int', '{', ';', '}', 'NUM'], # rdevfw(i{;}n
'param': [')', ','], # ),
'expression': [')', ';', ',', ']'], # );,]
'param_list': [')', ','], # ),
'call': ['==', ')', '*', ';', '+', '<', ',', '-', ']'], # q)*;+<,-]
'args': [')'], # )
'arg_list': [')', ','] # ),
}

actions = [
['program'],
################################################################# TODO: error on no main
['declaration_list','EOF'],
#################################################################
['declaration_list','declaration'],
['declaration'],
['var_declaration'],
['fun_declaration'],
['@hide_upper_scope', 'int', '@push_type', 'ID', '@store_var', '@unhide_upper_scope', ';'],
['@hide_upper_scope', 'int', '@push_type', 'ID', '@push_token', '[', 'NUM', '@push_token', '@assert_array_size',']', '@store_array_pointer', '@allocate_array', 'unhide_upper_scope',';'],
['@hide_upper_scope', 'int', '@push_type', 'ID', '@store_fun', '@start_scope', '(', 'params', ')', '@unhide_upper_scope', '#set_fun_adrs', 'compound_stmt', '@end_scope', '#jp_fun'],
['@hide_upper_scope', 'void','@push_type', 'ID', '@store_fun', '@start_scope', '(', 'params', ')', '@unhide_upper_scope', '#set_fun_adrs', 'compound_stmt', '@end_scope', '#jp_fun'],
['param_list'],
['void'],
['param_list',',','param'],
['param'],
['int', '@push_type', 'ID', '@store_var', '@store_fun_arg'],
['int', '@push_type', 'ID', '@push_token', '[', ']', '@store_array_parameter'],
['{', 'local_declarations','statement_list', '}'],
['local_declarations','var_declaration'],
[],
['statement_list','statement'],
[],
['expression_stmt'],
['@start_scope', 'compound_stmt', '@end_scope'],
['selection_stmt'],
['iteration_stmt'],
['return_stmt'],
['expression', '@assert_assign_type', '#assign',';'],
[';'],
['if','(','expression', '#save', ')','statement', '#jpf_save','else','statement', '#jp'],
['while','(', '#label', 'expression', '#save', ')','statement', '#end_while'],
['return', ';', '@assert_void_fun_return', '@return_void_fun'],
['return', 'expression', ';', '@assert_non_void_fun_return', '@return_value_fun'],
################################################################# TODO: doubt in expression_stmt
['var', '=', 'expression', '@assert_assign_type', '#assign'],
['simple_expression'],
#################################################################
['ID', '@push_variable'],
['ID', '@push_token', '[', 'expression', '@assert_array_index_in_size', '@push_array', ']'],
['additive_expression','relop','additive_expression', '@assert_compare_type'],
['additive_expression'],
################################################################# TODO: not sure about '#' place
#"RelTerm Expression == Expression #assert_compare_type #is_equal | Expression < Expression #assert_compare_type #is_lower",
['<', '#lt'],
['==', '#eq'],
#################################################################
['additive_expression','addop','term', '@reduce_assert_type', '@execute'],
['term'],
['+', '#add'],
['-', '#sub'],
['term', '*', '#mult', 'factor', '@reduce_assert_type', '@execute'],
['factor'],
['(','expression',')'],
['var'],
['call'],
['NUM', '@push_immediate'],
['ID', '@assert_fun', '@push_token', '@push_zero', '(','args', ')', '@assert_arg_count', '@call_fun'],
['arg_list'],
[],
['arg_list',',','expression', '@assert_exist_arg', '@put_arg'],
['expression', '@assert_exist_arg', '@put_arg']
]