LHS = [
'program_prime',
'program',
'declaration_list',
'declaration_list',
'declaration',
'declaration',
'var_declaration',
'var_declaration',
'fun_declaration',
'fun_declaration',
'params',
'params',
'param_list',
'param_list',
'param',
'param',
'compound_stmt',
'local_declarations',
'local_declarations',
'statement_list',
'statement_list',
'statement',
'statement',
'statement',
'statement',
'statement',
'expression_stmt',
'expression_stmt',
'selection_stmt',
'iteration_stmt',
'return_stmt',
'return_stmt',
'expression',
'expression',
'var',
'var',
'simple_expression',
'simple_expression',
'simple_expression',
'additive_expression',
'additive_expression',
'addop',
'addop',
'term',
'mulop',
'term',
'factor',
'factor',
'factor',
'factor',
'call',
'args',
'args',
'arg_list',
'arg_list',
'statement',
'output_stmt'
]

RHS = [
['program'],
['declaration_list','EOF'],
['declaration_list','declaration'],
['declaration'],
['var_declaration'],
['fun_declaration'],
['int','ID', ';'],
['int','ID', '[', 'NUM', ']', ';'],
['int','ID','(', 'params', ')', 'compound_stmt'],
['void','ID','(', 'params', ')', 'compound_stmt'],
['param_list'],
['void'],
['param_list',',','param'],
['param'],
['int', 'ID'],
['int','ID', '[', ']'],
['{', 'local_declarations','statement_list', '}'],
['local_declarations','var_declaration'],
[],
['statement_list','statement'],
[],
['expression_stmt'],
['compound_stmt'],
['selection_stmt'],
['iteration_stmt'],
['return_stmt'],
['expression',';'],
[';'],
['if','(','expression',')','statement','else','statement'],
['while','(','expression',')','statement'],
['return', ';'],
['return', 'expression', ';'],
['var', '=', 'expression'],
['simple_expression'],
['ID'],
['ID', '[', 'expression', ']'],
['additive_expression','<','additive_expression'],
['additive_expression','==','additive_expression'],
['additive_expression'],
['additive_expression','addop','term'],
['term'],
['+'],
['-'],
['term', 'mulop', 'factor'],
['*'],
['factor'],
['(','expression',')'],
['var'],
['call'],
['NUM'],
['ID', '(', 'args', ')'],
['arg_list'],
[],
['arg_list',',','expression'],
['expression'],
['output_stmt'],
['output', '(', 'expression', ')', ';']
]

follow = {
'declaration': ['EOF', 'void', 'int'],
'params': [')'],
'compound_stmt': ['ID', 'EOF', 'if', '(', 'int', 'NUM', 'output','return', 'else', 'void', 'while', '{', ';', '}'],
'declaration_list': ['EOF', 'void', 'int'],
'expression_stmt': ['output', 'return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # prsdfw({;}n
'fun_declaration': ['EOF', 'void', 'int'], # evi
'statement': ['output', 'return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # prsdfw({;}n
'selection_stmt': ['output', 'return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # prsdfw({;}n
'iteration_stmt': ['output', 'return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # prsdfw({;}n
'var': ['==', ')', '*', ';', '+', '<', ',', '=', '-', ']'], # q)*;+<,=-]
'simple_expression': [')', ';', ',', ']'], # );,]
'local_declarations': ['output', 'return', 'ID', 'if', 'while', '(', 'int', '{', ';', '}', 'NUM'], # prdfw(i{;}n
'term': ['==', ')', '*', ';', '+', '<', ',', '-', ']'], # q)*;+<,-]
'addop': ['ID', '(', 'NUM'], # d(n
'mulop': ['ID', '(', 'NUM'], # d(n
'program': ['$'], # $
'additive_expression': ['==', ')', ';', '+', '<', ',', '-', ']'], # q);+<,-]
'return_stmt': ['output', 'return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], # prsdfw({;}n
'statement_list': ['output', 'return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'], #prdfw({;}n
'factor': ['==', ')', '*', ';', '+', '<', ',', '-', ']'], # q)*;+<,-]
'var_declaration': ['output', 'return', 'ID', 'EOF', 'void', 'if', 'while', '(', 'int', '{', ';', '}', 'NUM'], # prdevfw(i{;}n
'param': [')', ','], # ),
'expression': [')', ';', ',', ']'], # );,]
'param_list': [')', ','], # ),
'call': ['==', ')', '*', ';', '+', '<', ',', '-', ']'], # q)*;+<,-]
'args': [')'], # )
'arg_list': [')', ','], # ),
'output_stmt': ['output', 'return', 'else', 'ID', 'if', 'while', '(', '{', ';', '}', 'NUM'],  # prsdfw({;}n
}

actions = [
['program'],
['declaration_list','EOF' , '@check_main'],
['declaration_list','declaration'],
['declaration'],
['var_declaration'],
['fun_declaration'],
['@hide_upper_scopes', 'int', '@push_stack', 'ID', '@define_var', '@unhide_upper_scopes', ';'],
['@hide_upper_scopes', 'int', '@push_stack', 'ID', '@push_stack', '[', 'NUM', '@push_stack', '@check_array_size',']', '@define_array', '#allocate_array', '@unhide_upper_scopes',';'],
['@hide_upper_scopes', 'int', '@push_stack', 'ID', '@define_fun', '@open_scope', '(', 'params', ')', '@unhide_upper_scopes', '#set_fun_adrs', 'compound_stmt', '@close_scope', '#jp_fun'],
['@hide_upper_scopes', 'void','@push_stack', 'ID', '@define_fun', '@open_scope', '(', 'params', ')', '@unhide_upper_scopes', '#set_fun_adrs', 'compound_stmt', '@close_scope', '#jp_fun'],
['param_list'],
['void'],
['param_list',',','param'],
['param'],
['int', '@push_stack', 'ID', '@define_var', '@set_fun_arg'],
['int', '@push_stack', 'ID', '@push_stack', '[', ']', '@store_array_parameter'],
['{', 'local_declarations','statement_list', '}'],
['local_declarations','var_declaration'],
[],
['statement_list','statement'],
[],
['expression_stmt'],
['@open_scope', 'compound_stmt', '@close_scope'],
['selection_stmt'],
['iteration_stmt'],
['return_stmt'],
['expression',';'],
[';'],
['if','(','expression', ')', '#save','statement', 'else','#jpf_save','statement', '#jp'],
['while','(', '#label', 'expression', '#save', ')','statement', '#end_while'],
['return', ';', '@check_void_fun_return', '#return_void_fun'],
['return', 'expression', ';', '@check_int_fun_return', '#return_int_fun'],
['var', '=', 'expression', '@check_type', '#assign'],
['simple_expression'],
['ID', '@push_variable'],
['ID', '@push_stack', '[', 'expression', '@check_array_bound', '#push_array', ']'],
['additive_expression','<','additive_expression', '@check_type', '#lt'],
['additive_expression','==','additive_expression', '@check_type', '#eq'],
['additive_expression'],
['additive_expression','addop','term', '@operation_type_check', '#execute'],
['term'],
['+', '#add'],
['-', '#sub'],
['term', 'mulop', 'factor', '@operation_type_check', '#execute'],
['*', '#mult'],
['factor'],
['(','expression',')'],
['var'],
['call'],
['NUM', '@push_immediate'],
['ID', '@check_is_fun', '@push_stack', '@push_arg_len', '(','args', ')', '@check_arg_count', '#call_fun'],
['arg_list'],
[],
['arg_list',',','expression', '@check_exist_arg', '#set_arg'],
['expression', '@check_exist_arg', '#set_arg'],
['output_stmt'],
['output', '(', 'expression', '@check_int_argument', '#print_op',')', ';']
]